name: test

on:
  push:
  pull_request:

jobs:
  test1:
    runs-on: ubuntu-18.04
    if: (github.event_name != 'pull_request')
    steps:
    - name: Print
      run: |
        echo "TEST 1"

  test2:
    runs-on: ubuntu-18.04
    if: (github.event_name == 'pull_request')
    steps:
    - name: Print
      run: |
        echo "TEST 2"
