name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Do the test
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
           echo "::set-output name=foreign_pr::yes"
        else
           echo "::set-output name=foreign_pr::"
	fi
