name: test

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-18.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Execute tests
        run: exit 0

  test1:
    runs-on: ubuntu-18.04
    needs: check
    steps:
    - name: Work1
      run: |
        echo "Do work1"

  test2:
    runs-on: ubuntu-18.04
    needs: check
    steps:
    - name: Work2
      run: |
        echo "Do work2"
