name: test

on:
  # Run on every push of the branch
  push:

  # Never run or show up on any pull request!
  pull_request:
    branches-ignore:
      - '*'

jobs:
  run-once:
    runs-on: ubuntu-18.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Skip Local PRs
        run: exit 0

  test1:
    runs-on: ubuntu-18.04
    needs: run-once
    steps:
    - name: Work1
      run: |
        echo "Do work1"

  test2:
    runs-on: ubuntu-18.04
    needs: run-once
    steps:
    - name: Work2
      run: |
        echo "Do work2"
