name: test

env:
local_PR: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

on:
  push:
  pull_request:

jobs:
  test1:
    runs-on: ubuntu-18.04
    if: ${{ env.local_PR }}
    steps:
    - name: Work
      run: |
        echo "Do work"
