name: test

on:
  push:
  pull_request:

jobs:
  run-once:
    runs-on: ubuntu-18.04
    if: !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'mfem/mfem')
    steps:
      - name: Skip Local PRs
        run: |
          echo "Do work1"

  test1:
    runs-on: ubuntu-18.04
    needs: run-once
    steps:
    - name: Work1
      run: |
        echo "Do work1"

  test2:
    runs-on: ubuntu-18.04
    needs: run-once
    steps:
    - name: Work2
      run: |
        echo "Do work2"
